/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.mobilevle.messenger;

public final class R {
    public static final class array {
        public static final int contact_interval_array=0x7f060003;
        public static final int contact_interval_values=0x7f060002;
        public static final int message_interval_array=0x7f060001;
        public static final int message_interval_values=0x7f060000;
        public static final int search_field_array=0x7f060004;
        public static final int search_field_values=0x7f060005;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int generic_background=0x7f020000;
        public static final int ic_contacts_state=0x7f020001;
        public static final int ic_conversation_state=0x7f020002;
        public static final int ic_menu_conversation=0x7f020003;
        public static final int ic_menu_conversation_invert=0x7f020004;
        public static final int ic_menu_edit=0x7f020005;
        public static final int ic_menu_edit_invert=0x7f020006;
        public static final int ic_menu_friendslist=0x7f020007;
        public static final int ic_menu_friendslist_invert=0x7f020008;
        public static final int ic_menu_manage=0x7f020009;
        public static final int ic_menu_manage_invert=0x7f02000a;
        public static final int ic_menu_message=0x7f02000b;
        public static final int ic_menu_refresh=0x7f02000c;
        public static final int ic_menu_search=0x7f02000d;
        public static final int ic_menu_send=0x7f02000e;
        public static final int ic_settings_state=0x7f02000f;
        public static final int login_background=0x7f020010;
        public static final int mvle=0x7f020011;
        public static final int new_message=0x7f020012;
        public static final int sym_message=0x7f020013;
    }
    public static final class id {
        public static final int auto_complete_recipients=0x7f080000;
        public static final int buttonSignIn=0x7f080010;
        public static final int communicant_name=0x7f080009;
        public static final int list_header_title=0x7f08000d;
        public static final int message_content=0x7f080001;
        public static final int message_date=0x7f08000c;
        public static final int message_send=0x7f080002;
        public static final int message_summary=0x7f08000b;
        public static final int messages_communicant_name=0x7f080006;
        public static final int messages_list=0x7f080003;
        public static final int messages_message_content=0x7f080007;
        public static final int messages_message_date=0x7f080008;
        public static final int reply=0x7f080005;
        public static final int reply_content=0x7f080004;
        public static final int results_field_text=0x7f080015;
        public static final int results_list=0x7f080016;
        public static final int search=0x7f080014;
        public static final int search_field=0x7f080013;
        public static final int search_field_text=0x7f080012;
        public static final int search_value=0x7f080011;
        public static final int subject_summary=0x7f08000a;
        public static final int txtPassword=0x7f08000f;
        public static final int txtUserName=0x7f08000e;
        public static final int user_full_name=0x7f080017;
        public static final int user_username=0x7f080018;
    }
    public static final class layout {
        public static final int compose_message_layout=0x7f030000;
        public static final int conversation_layout=0x7f030001;
        public static final int conversation_message_list=0x7f030002;
        public static final int conversation_primer_list=0x7f030003;
        public static final int conversation_primer_list_header=0x7f030004;
        public static final int login=0x7f030005;
        public static final int main_tab_screen=0x7f030006;
        public static final int search_contacts_layout=0x7f030007;
        public static final int users_list=0x7f030008;
    }
    public static final class raw {
        public static final int vlehandler=0x7f050000;
    }
    public static final class string {
        public static final int alert_tone_key=0x7f07000a;
        public static final int app_name=0x7f070000;
        public static final int contact_interval_default=0x7f070006;
        /**  1 minute in millis 
         */
        public static final int contact_interval_key=0x7f070005;
        public static final int edit_preferences=0x7f070002;
        public static final int invalid_session_message=0x7f070013;
        public static final int message_alert_key=0x7f070009;
        public static final int message_interval_default=0x7f070004;
        public static final int message_interval_key=0x7f070003;
        public static final int message_vibrate_key=0x7f07000b;
        public static final int messenger=0x7f070001;
        public static final int moodle_pwd_key=0x7f070008;
        /**  720000 2 hours in millis 
         */
        public static final int moodle_user_key=0x7f070007;
        public static final int new_message=0x7f07000c;
        public static final int no_contacts=0x7f070014;
        public static final int no_messages=0x7f070015;
        public static final int results_field_text=0x7f070012;
        public static final int search=0x7f07000e;
        public static final int search_field_key=0x7f07000d;
        public static final int search_field_text=0x7f070011;
        public static final int search_prompt=0x7f070010;
        public static final int send=0x7f07000f;
    }
    public static final class xml {
        public static final int messenger_preferences=0x7f040000;
    }
}
